### ISSUE TITLE
Build and build:min commands differences

### ISSUE THREAD

**Issue by meoke** [jankapunkt/npm-package-template#3]
Hi! I am not sure if I understand correctly. Could you help me with that?
"Build" command transpiles via Babel all files from the lib folder. But the "build:min" minifies only dist/index.js? Is that intended? So  if I plan to have more than one file in the lib folder I should use e.g. webpack or another tool to minify them all at once?

**Comment by jankapunkt** [comment]
Hi, this is indeed an issue. I would like to keep webpack out of this but babel itself can't merge files (to my current knowledge).

What do you think about using  rollup to merge files? I think minification makes only sense if there is one file to target so merging files should definitely be part of the build pipeline. What do you think?

**Comment by meoke** [comment]
Rollup works perfectly, thanks! I've just configured it in my repository and also created a pull request #4 for this template.
