### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/npm-package-template#48]
Keep the dev-dependencies up to date

**Comment by killerkc12** [comment]
@jankapunkt I would like to work on this. Please assign to me

**Comment by jankapunkt** [comment]
hi @killerkc12 please go for it but only update `package.json` and ignore `package-lock.json`.

**Comment by killerkc12** [comment]
@jankapunkt I'm not able to generate the PR, can you help me with this?
![image](https://github.com/jankapunkt/npm-package-template/assets/50802786/7472f64f-c8fb-4a5d-97ff-a9ac8cb598c3)

**Comment by jankapunkt** [comment]
Hey @killerkc12 it looks like something went from when creating the new branch? Everything shows "initial commit".

you can try to fix this by the following steps:

1. copy the content of `package.json` into en external editor like notpad
2. on your `fix-devdependencies` branch enter `git reset --hard 17acc44b2dde7cf6e5818831fa2cdbfbdf94443b`
3. paste the the content into package.json and commit
4. update the branch via `git push origin fix-devdependencies`

**Comment by killerkc12** [comment]
@jankapunkt #49 is created Kindly review it.
