### ISSUE TITLE
Warnings on npm install

### ISSUE THREAD

**Issue by dhowe** [jankapunkt/npm-package-template#53]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @rollup/pluginutils@5.0.2
npm WARN Found: rollup@4.1.4
npm WARN node_modules/rollup
npm WARN   dev rollup@"^4.0.2" from the root project
npm WARN   2 more (@rollup/plugin-babel, @rollup/plugin-commonjs)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional rollup@"^1.20.0||^2.0.0||^3.0.0" from @rollup/pluginutils@5.0.2
npm WARN node_modules/@rollup/pluginutils
npm WARN   @rollup/pluginutils@"^5.0.1" from @rollup/plugin-babel@6.0.4
npm WARN   node_modules/@rollup/plugin-babel
npm WARN   1 more (@rollup/plugin-commonjs)
npm WARN 
npm WARN Conflicting peer dependency: rollup@3.29.4
npm WARN node_modules/rollup
npm WARN   peerOptional rollup@"^1.20.0||^2.0.0||^3.0.0" from @rollup/pluginutils@5.0.2
npm WARN   node_modules/@rollup/pluginutils
npm WARN     @rollup/pluginutils@"^5.0.1" from @rollup/plugin-babel@6.0.4
npm WARN     node_modules/@rollup/plugin-babel
npm WARN     1 more (@rollup/plugin-commonjs)

**Comment by jankapunkt** [comment]
Please review #55
